apiVersion: v1
kind: Service
metadata:
  name: christmaslyrics-service
  labels: 
    app: christmaslyrics-app
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: christmaslyrics-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: https
