apiVersion: apps/v1
kind: Deployment
metadata:
  name: christmaslyrics-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: christmaslyrics-app
  template:
    metadata:
      labels:
        app: christmaslyrics-app
    spec:
      containers:
      - name: christmaslyrics-app-container
        image: ifyagu/christmaslyrics-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - port: 80
        - targetPort: 80  
 # strategy:
  #  type: RollingUpdate
   # rollingUpdate:
    #  maxiUnavailable: 1 

