apiVersion: apps/v1
kind: Deployment
metadata:
  name: christmaslyrics-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: christmaslyrics-app
  template:
    metadata:
      labels:
        app: christmaslyrics-app
    spec:
      containers:
      - name: christmaslyrics-app-container
        image: ifyagu/christmaslyrics-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        #- port: 5001  
 # strategy:
  #  type: RollingUpdate
   # rollingUpdate:
    #  maxiUnavailable: 1 

